// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBidFN3gJXkuYVj_N-6sy7YAJ4cV9KRllk',
    appId: '1:1014493681333:web:924afb5f2f78143574d0fc',
    messagingSenderId: '1014493681333',
    projectId: 'healthy-ways-77bc0',
    authDomain: 'healthy-ways-77bc0.firebaseapp.com',
    storageBucket: 'healthy-ways-77bc0.firebasestorage.app',
    measurementId: 'G-VT3X7RK3F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCimFQ4NyxyGDs3zjHgfGNmQb1cxonxEaM',
    appId: '1:1014493681333:android:321b3efa739b8a2a74d0fc',
    messagingSenderId: '1014493681333',
    projectId: 'healthy-ways-77bc0',
    storageBucket: 'healthy-ways-77bc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9BM8kBslTsCHO5sE8tk0CY4mzIAs0szA',
    appId: '1:1014493681333:ios:da493b61700f96d474d0fc',
    messagingSenderId: '1014493681333',
    projectId: 'healthy-ways-77bc0',
    storageBucket: 'healthy-ways-77bc0.firebasestorage.app',
    iosBundleId: 'com.example.healtyWays',
  );
}
